### ISSUE TITLE
在启动的时候为什么会报这个错呢

### ISSUE THREAD

**Issue by mybydhn** [icepy/openapi-nodejs-index-oa-template#1]
E:\projects\openapi-nodejs-index-oa-template-master\app\controller\OAuth\index.js:20
    let origUrlObj = url.parse(origUrl);
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\projects\openapi-nodejs-index-oa-template-master\app\api\index.js:6:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by icepy** [comment]
你这个是url解析不对，你得传一个带 `#` 正常的URL
